name: pr

on: 
  push:
    branches:
      - "!master"
  pull_request:
    branches:
      - master

jobs:
#   spellcheck:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2.0.0
#     - name: Spellcheck Action
#       uses: rojopolis/spellcheck-github-actions@0.2.0
  check_links:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2.0.0
    - name: check_links
      uses: docker://dkhamsing/awesome_bot:latest
      with:
        args: --white-list "example.com" --allow 429 --allow-timeout -t 10 --skip-save-results --allow-dupe --allow-redirect README.md Info//cryptography.md Info//networking.md Info//attacks.md Info//social_engineering.md Info//siem.md Info//cloud.md Info//compliance.md Info//general_info.md Info//iam.md Info//os.md Info//activedirectory.md Info//containers.md Info//osi.md Info//shell.md
    
