name: pr

on: 
  push:
    branches:
      - "!master"
  pull_request:
    branches:
      - master

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Spellcheck Action
      uses: rojopolis/spellcheck-github-actions@0.2.0
  check_links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - uses: docker://dkhamsing/awesome_bot:latest
      with:
        args: --allow-dupe --allow-redirect /github/workspace/README.md
    
